### ISSUE TITLE
初始化显示地点可能有问题

### ISSUE THREAD

**Issue by Zrincet** [fineemb/lovelace-cn-map-card#3]
配置完成后，默认显示的是北京，  
![](https://hozoy-1251133838.cos.ap-shanghai.myqcloud.com/20200718223204.png)  
更换Chrome浏览器后问题依旧  
但在手机浏览器上显示正常，但当我把设置的地点更换为另外一个地点时，手机浏览器还是显示的最初配置的那个地点， PC上还是显示的北京。是不是初始化地点可能有问题。  
key是自己申请的 后台可以看到调用记录没问题

**Comment by fineemb** [comment]
更新新版后观察， 应该已经修复
