### ISSUE TITLE
116.2出现错误

### ISSUE THREAD

**Issue by Tao173** [fineemb/lovelace-cn-map-card#6]
Logger: frontend.js.latest.202010012
Source: components/system_log/__init__.py:193
First occurred: 下午1:22:51 (2 occurrences)
Last logged: 下午1:22:53

:0:0 Script error.
http://192.168.1.100:8123/hacsfiles/lovelace-cn-map-card/cn-map-card.js:76:18 Uncaught TypeError: Cannot read property 'setPitch' of undefined

**Comment by mildrabbit** [comment]
同样116.2出现报错：

 Error: Custom element not found: gaode-map-card 


Custom element doesn't exist: gaode-map-card.

type: 'custom:gaode-map-card'
default_zoom: '9'
dark_mode: false
hours_to_show: '168'
entities:
  - person.a
  - person.b
  - person.c
  - zone.school
  - zone.home
key: 08fa99f275c4003690
title: Map

**Comment by fineemb** [comment]
新版再试试,

**Comment by GWan1234** [comment]
> 新版再试试,

我这正常了，谢谢
