### ISSUE TITLE
App中显示不正常

### ISSUE THREAD

**Issue by georgezhao2010** [fineemb/lovelace-cn-map-card#8]
在iPhone的HomeAssistant App中，地图被分成了三个横条，完全看不出来哪是哪。电脑端基本是正常的。

![IMG_20201110_204300](https://user-images.githubusercontent.com/27534713/98676015-fc9a4500-2395-11eb-8fb6-96c0795b3da0.PNG)

**Comment by fineemb** [comment]
这个确实是个bug。一是缺少ios设备。也不知道这个app怎么调试。 但是据说Safari 都是正常的。

**Comment by fineemb** [comment]
Duplicate of #4

**Comment by georgezhao2010** [comment]
> 这个确实是个bug。一是缺少ios设备。也不知道这个app怎么调试。 但是据说Safari 都是正常的。

那我把HomeAssistant的内置浏览器换成Safari试试
